type Locker @entity {
  id: ID!
  owner: String! @index
  treasury: String
  operator: String
  timestamp: BigInt!
  address: String!
  unlocked: Boolean!
  referrer: String!
}

type Adapter @entity {
  id: ID!
  address: String! @index
  protocol: String!
  locker: String! @index
}

type LPToken @entity {
  id: ID!
  address: String!
  name: String
  symbol: String
}

# ----------------------------------------------------
#             Vault Deposits and Withdrawals
# ----------------------------------------------------
type LockerDeposit @entity {
  id: ID!
  locker: String! @index
  token: String!
  amountOrId: BigInt!
  timestamp: BigInt!
  lockExpiration: BigInt
  transactionHash: String!
}

type LockerWithdrawal @entity {
  id: ID!
  locker: String! @index
  token: String!
  amountOrId: BigInt!
  timestamp: BigInt!
  transactionHash: String!
}

# tracks final state of a vault deposit
# so all deposits minus all withdrawals
type LockerTotalDeposit @entity {
  id: ID!
  locker: String! @index
  token: String!
  amount: BigInt!
  nftIds: [String]
  lockExpiration: BigInt
}

# ----------------------------------------------------
#                     Vault Actions
# ----------------------------------------------------
type LockerStake @entity {
  id: ID!
  locker: String! @index
  vault: String! @index
  token: String!
  amountOrId: BigInt!
  timestamp: BigInt!
  transactionHash: String!
}

type LockerUnstake @entity {
  id: ID!
  locker: String! @index
  vault: String! @index
  token: String!
  amountOrId: BigInt!
  timestamp: BigInt!
  transactionHash: String!
}

type LockerTotalStake @entity {
  id: ID!
  locker: String! @index
  vault: String! @index
  token: String!
  amount: BigInt!
  nftIds: [String]
}

type LockerRewardsClaim @entity {
  id: ID!
  locker: String! @index
  vault: String! @index
  token: String!
  amount: BigInt!
  timestamp: BigInt!
  transactionHash: String!
}

type LockerWildcard @entity {
  id: ID!
  locker: String! @index
  vault: String! @index
  func: Int!
  args: String!
  timestamp: BigInt!
  transactionHash: String!
}

# ----------------------------------------------------
#                     Vault Adapters
# ----------------------------------------------------
type AdapterRegistered @entity {
  id: ID!
  locker: String! @index
  protocol: String!
  adapter: String!
  timestamp: BigInt!
  transactionHash: String!
}

type AdapterUpgraded @entity {
  id: ID!
  locker: String! @index
  protocol: String!
  newImplementation: String!
  timestamp: BigInt!
  transactionHash: String!
}

# ----------------------------------------------------
#                     Misc
# ----------------------------------------------------

type Fees @entity {
  id: ID!
  referral: String!
  token: String!
  amount: BigInt!
  transactionHash: String!
  timestamp: BigInt!
}

type BGTDelegation @entity {
  id: ID!
  locker: String! @index
  validator: String!
  queued: BigInt!
  activated: BigInt!
}

type XKDKFinalizedRedeem @entity {
  id: ID!
  locker: String! @index
  amount: BigInt!
  timestamp: BigInt!
  transactionHash: String!
}

type XKDKRedeem @entity {
  id: ID!
  locker: String! @index
  xKodiakAmount: BigInt!
  kodiakAmount: BigInt!
  duration: BigInt!
  timestamp: BigInt!
  transactionHash: String!
}

type LockerBalance @entity {
  id: ID!
  locker: String! @index
  token: String! @index
  balance: BigInt!
}
